Add initial traefik support
redhat-nfvpe/ansible-cira pull request #106
Opened 2017-03-13 21:22 UTC by leifmadsen

Adding initial traefik support to start wrapping our web services
with a reverse proxy to keep the number of ports being exposed much
simpler.

Closes #93

2017-03-13 21:36 UTC, dougbtv requested changes

2017-03-13 21:36 UTC, dougbtv commented on docker-compose.yml
> +      - "443:443"
Looks like there's a conflicting 443 allocation for Kibana later in the file (I wouldn't've found it, but, Travis did!)

2017-03-14 02:22 UTC, leifmadsen commented
Currently a WIP, please do not merge.

2017-03-14 04:58 UTC, s1061123 commented
Hi Leif, 

I'm wondering whether traefik makes network easier or not in our docker-compose case.
Currently our docker-compose scenario is mainly for one container host hence nothing is different between with traefic and without traefic. Without traefic, docker-compose expose works fine. Traefic is very useful in case of multi-host container environment, such as docker-swarm, k8s and mesos, so your plan is good for future use case scenario.

So how about to make separate docker-compose.yaml for 

- one container host scenario  (without traefic)
- multi container-host scenario (with traefic)?

2017-03-14 18:23 UTC, leifmadsen commented on docker-compose.yml
> +      - "443:443"
Fixed!

2017-03-14 18:31 UTC, leifmadsen commented
@s1061123 (I know we talked today and think we're on the same page, but for historical reference, I'll comment below to your questions above.)

I think for now traefik doesn't really add any complexity that makes it harder to deploy TOAD than it is now, in fact I think it makes it bit simpler since you don't need to know the specific ports for connecting to the services. Right now, you would connect to Jenkins via:  http://toad.tld/jenkins and everything would just route.

If you don't want to use a hostname (specified via your `/etc/hosts` file for example), then you could override the `.env` file with your own `PROXY_DOMAIN` that points at the IP address that you want to listen on (untested).

Overall, I think while it doesn't add a lot to the system as it stands, it is a good tool for helping to future proof a dynamic scaling scenario, and also for the cases where we want to deal with life cycle management, allowing for two containers to live simultaneously behind the proxy, in order to upgrade the software running in that container.

2017-03-14 19:01 UTC, dougbtv approved these changes

2017-03-14 19:03 UTC, merged